# Generated by Django 4.0.4 on 2022-04-21 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='google_account',
            new_name='eccPart',
        ),
    ]
