# Generated by Django 4.0.4 on 2022-04-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_google_account_account_eccpart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='eccPart',
            field=models.CharField(max_length=900),
        ),
    ]
