# Generated by Django 4.0.4 on 2022-04-23 01:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_eccpart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='eccPart',
        ),
        migrations.AddField(
            model_name='account',
            name='eccPart1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='eccPart2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='eccPart3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='eccPart4',
            field=models.CharField(default=datetime.datetime(2022, 4, 23, 1, 22, 7, 318998, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
